model:
  pruned_model_path: 'models/segformer_pruned_model'
  feature_extractor_path: 'models/segformer_feature_extractor'

uploads:
  folder: 'backend/uploads'
  allowed_extensions: ['jpg', 'jpeg', 'png', 'gif']

app:
  secret_key: 'SECRET_KEY'
  debug: true

labels:
  folder: 'backend/labels'
